[project]
authors = ["Jeremy Tuloup <jeremy.tuloup@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "compound-interest-calculator"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.3.2,<5"
voila = ">=0.5.8,<0.6"
ipecharts = ">=1.0.8,<2"
ipywidgets = ">=8.1.5,<9"
pip = ">=24.3.1,<25"
numpy = ">=2.2.0,<3"
